### ISSUE TITLE
Update assets and NFT view to new UI

### ISSUE THREAD

**Issue by carlosbleck** [Open-Verifik/zelf-online-version#27]
# Description
Change the assets and NFT view to new UI

## TODO:

- [ ] Change assets to new UI
- [ ] Change NFT to new UI
- [ ] Add functionality to assets and NFT view
